/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Abbrs: typeof import('./src/renderer/src/components/Abbrs/index.vue')['default']
    Button: typeof import('./src/renderer/src/components/Button/index.vue')['default']
    ContentBox: typeof import('./src/renderer/src/components/ContentBox/index.vue')['default']
    ContentLayout: typeof import('./src/renderer/src/components/ContentLayout/index.vue')['default']
    Debugger: typeof import('./src/renderer/src/components/Debugger/index.vue')['default']
    Markdown: typeof import('./src/renderer/src/components/Markdown/index.vue')['default']
    McpName: typeof import('./src/renderer/src/components/McpName/index.vue')['default']
    ModelName: typeof import('./src/renderer/src/components/ModelName/index.vue')['default']
    MonacoEditor: typeof import('./src/renderer/src/components/MonacoEditor/index.vue')['default']
    MsgBubble: typeof import('./src/renderer/src/components/MsgBubble/index.vue')['default']
    PopConfirm: typeof import('./src/renderer/src/components/PopConfirm/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SubNavLayout: typeof import('./src/renderer/src/components/SubNavLayout/index.vue')['default']
    Svg: typeof import('./src/renderer/src/components/Svg/index.vue')['default']
    SvgPicker: typeof import('./src/renderer/src/components/SvgPicker/index.vue')['default']
    Switch: typeof import('./src/renderer/src/components/Switch/index.vue')['default']
    Table: typeof import('./src/renderer/src/components/Table/index.vue')['default']
  }
}

// For TSX support
declare global {
  const Abbrs: typeof import('./src/renderer/src/components/Abbrs/index.vue')['default']
  const Button: typeof import('./src/renderer/src/components/Button/index.vue')['default']
  const ContentBox: typeof import('./src/renderer/src/components/ContentBox/index.vue')['default']
  const ContentLayout: typeof import('./src/renderer/src/components/ContentLayout/index.vue')['default']
  const Debugger: typeof import('./src/renderer/src/components/Debugger/index.vue')['default']
  const Markdown: typeof import('./src/renderer/src/components/Markdown/index.vue')['default']
  const McpName: typeof import('./src/renderer/src/components/McpName/index.vue')['default']
  const ModelName: typeof import('./src/renderer/src/components/ModelName/index.vue')['default']
  const MonacoEditor: typeof import('./src/renderer/src/components/MonacoEditor/index.vue')['default']
  const MsgBubble: typeof import('./src/renderer/src/components/MsgBubble/index.vue')['default']
  const PopConfirm: typeof import('./src/renderer/src/components/PopConfirm/index.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SubNavLayout: typeof import('./src/renderer/src/components/SubNavLayout/index.vue')['default']
  const Svg: typeof import('./src/renderer/src/components/Svg/index.vue')['default']
  const SvgPicker: typeof import('./src/renderer/src/components/SvgPicker/index.vue')['default']
  const Switch: typeof import('./src/renderer/src/components/Switch/index.vue')['default']
  const Table: typeof import('./src/renderer/src/components/Table/index.vue')['default']
}