packages:
  - demo/*
  - packages/*

catalogs:
  common:
    '@toolmain/components': ^1.2.23
    '@toolmain/libs': ^1.1.13
    '@toolmain/shared': ^1.3.4
    ajv: ^8.17.1
    ajv-errors: ^3.0.0
    apache-arrow: ^21.1.0
    axios: ^1.13.2
    chance: ^1.1.13
    filesize: ^11.0.13
    js-tiktoken: ^1.0.21
    json5: ^2.2.3
    mime-types: ^3.0.2
    nanoid: ^5.1.6
    p-queue: ^9.1.0
  dev:
    '@babel/types': ~7.28.6
    '@commitlint/config-conventional': ^20.3.1
    '@electron/notarize': ^3.1.1
    '@eslint/js': ^9.39.2
    '@iconify/json': ^2.2.430
    '@iconify/types': ^2.0.0
    '@rollup/plugin-json': ^6.1.0
    '@types/chance': ^1.1.7
    '@types/estree': ^1.0.8
    '@types/hash-sum': ^1.0.2
    '@types/hast': ^3.0.4
    '@types/lodash.merge': ^4.6.9
    '@types/mime-types': ^3.0.1
    '@types/node': ^25.0.9
    '@types/pdf-parse': ^1.1.5
    '@types/sqlstring': ^2.3.2
    '@types/unist': ^3.0.3
    '@typescript-eslint/eslint-plugin': ^8.53.1
    '@unocss/preset-icons': ^66.6.0
    '@vitejs/plugin-vue': ^6.0.3
    '@vitejs/plugin-vue-jsx': ^5.1.3
    '@vitest/browser': ^4.0.17
    '@vitest/browser-playwright': ^4.0.17
    '@vitest/coverage-v8': ^4.0.17
    '@vitest/ui': ^4.0.17
    '@vue/test-utils': ^2.4.6
    commitlint: ^20.3.1
    csstype: ^3.2.3
    devlop: ^1.1.0
    electron: ^39.2.7
    electron-builder: ^26.0.20
    electron-vite: ^5.0.0
    eslint: ^9.39.2
    eslint-config-prettier: ^10.1.8
    eslint-plugin-import: ^2.32.0
    eslint-plugin-n: ^17.23.2
    eslint-plugin-prettier: ^5.5.5
    eslint-plugin-promise: ^7.2.1
    eslint-plugin-vue: ^10.7.0
    globals: ^17.0.0
    husky: ^9.1.7
    jsdom: ^27.4.0
    lint-staged: ^16.2.7
    mdast-util-mdx-expression: ^2.0.1
    mdast-util-mdx-jsx: ^3.2.0
    mdast-util-mdxjs-esm: ^2.0.1
    msw: ^2.12.7
    playwright: ^1.57.0
    prettier: ^3.8.0
    prettier-eslint: ^16.4.2
    rollup: ^4.55.2
    rollup-plugin-dts: ^6.3.0
    rollup-plugin-esbuild: ^6.2.1
    rollup-plugin-visualizer: ^6.0.5
    sass: ^1.97.2
    style-value-types: ^5.1.2
    terser: ^5.46.0
    tsx: ^4.21.0
    type-fest: ^5.4.1
    typescript: ^5.9.3
    typescript-eslint: ^8.53.1
    unocss: ^66.6.0
    unplugin-auto-import: ^21.0.0
    unplugin-icons: ^23.0.1
    unplugin-vue-components: ^31.0.0
    vite: ^7.3.1
    vite-node: ^5.3.0
    vite-plugin-vue-devtools: ^8.0.5
    vitest: ^4.0.17
    vitest-browser-vue: ^2.0.1
    vue-eslint-parser: ^10.2.0
    vue-tsc: ^3.2.2
  node:
    '@electron-toolkit/preload': ^3.0.2
    '@electron-toolkit/utils': ^4.0.0
    '@file-type/xml': ^0.4.4
    '@lancedb/lancedb': ^0.22.3
    '@modelcontextprotocol/sdk': ^1.25.3
    csv-parser: ^3.2.0
    electron-log: ^5.4.3
    electron-store: ^11.0.2
    electron-updater: ^6.7.3
    electron-window-state: ^5.0.3
    exceljs: ^4.4.0
    execa: ^9.6.1
    file-type: ^21.3.0
    mammoth: ^1.11.0
    pdf-parse: ^2.4.5
    sqlstring: ^2.3.3
  web:
    '@iconify/utils': ^3.1.0
    '@shikijs/monaco': ^3.21.0
    '@unocss/reset': 66.6.0
    '@vueuse/core': ^14.1.0
    character-entities: ^2.0.2
    comma-separated-tokens: ^2.0.3
    dexie: ^4.2.1
    element-plus: ^2.13.1
    estree-util-is-identifier-name: ^3.0.0
    hast-util-whitespace: ^3.0.0
    hotkeys-js: ^4.0.0
    html-url-attributes: ^3.0.1
    mermaid: ^11.12.2
    monaco-editor: ^0.55.1
    openai: ^6.16.0
    pinia: ^3.0.4
    property-information: ^7.1.0
    rehype-mathjax: ^7.1.0
    rehype-stringify: ^10.0.1
    remark-emoji: ^5.0.2
    remark-gfm: ^4.0.1
    remark-math: ^6.0.0
    remark-parse: ^11.0.0
    remark-rehype: ^11.1.2
    remark-squeeze-paragraphs: ^6.0.0
    shiki: ^3.21.0
    space-separated-tokens: ^2.0.2
    style-to-js: ^1.1.21
    unified: ^11.0.5
    unist-util-visit: ^5.0.0
    vfile: ^6.0.3
    vfile-message: ^4.0.3
    vue: ^3.5.27
    vue-i18n: ^11.2.8
    vue-router: ^4.6.4

onlyBuiltDependencies:
  - esbuild
  - vue-demi
  - '@parcel/watcher'
  - electron
  - electron-winstaller
  - msw
  - protobufjs

overrides:
  decode-named-character-reference: file:./src/renderer/patchs/decode-named-character-reference
