import { ModelType, ProviderMeta, ModelActiveStatus } from "@windflow/core/types"
import { uniqueId } from "@toolmain/shared"
export const providerDefault = (): ProviderMeta[] => {
  return [
    {
      id: uniqueId(),
      name: "deepseek",
      logo: "",
      alias: "深度求索",
      api: {
        doc: "https://api-docs.deepseek.com/zh-cn/",
        url: "https://api.deepseek.com",
        key: "",
        models: { method: "GET", url: "/models" },
        llmChat: { method: "POST", url: "/chat/completions" },
        balance: { method: "GET", url: "/user/balance" },
      },
      selectedTypes: [ModelType.Chat],
      selectedSubProviders: ["deepseek"],
      activeStatus: ModelActiveStatus.All,
    },
    {
      id: uniqueId(),
      name: "siliconflow",
      alias: "硅基流动",
      logo: "",
      api: {
        doc: "https://docs.siliconflow.cn/cn/api-reference",
        url: "https://api.siliconflow.cn/v1",
        key: "",
        models: { method: "GET", url: "/models" },
        llmChat: { method: "POST", url: "/chat/completions" },
        balance: { method: "GET", url: "/user/info" },
        textToImage: { method: "POST", url: "/images/generations" },
        embedding: { method: "POST", url: "/embeddings" },
        rerank: { method: "POST", url: "/rerank" },
        imageToText: { method: "GET", url: "" },
        textToVideo: { method: "GET", url: "" },
        speechToText: { method: "GET", url: "" },
        textToSpeech: { method: "GET", url: "" },
      },
      selectedTypes: [ModelType.Chat],
      selectedSubProviders: [],
      activeStatus: ModelActiveStatus.All,
    },
    {
      id: uniqueId(),
      name: "volcengine",
      alias: "火山引擎",
      logo: "",
      api: {
        doc: "https://www.volcengine.com/docs/82379/1263272",
        url: "https://ark.cn-beijing.volces.com/api/v3",
        key: "",
        models: { method: "GET", url: "" },
        llmChat: { method: "POST", url: "/chat/completions" },
        balance: { method: "GET", url: "" },
        textToImage: { method: "GET", url: "" },
        imageToText: { method: "GET", url: "" },
        textToVideo: { method: "GET", url: "" },
        speechToText: { method: "GET", url: "" },
        textToSpeech: { method: "GET", url: "" },
      },
      selectedTypes: [ModelType.Chat],
      selectedSubProviders: [],
      activeStatus: ModelActiveStatus.All,
    },
    {
      id: uniqueId(),
      name: "openai",
      alias: "OpenAI",
      logo: "",
      api: {
        doc: "https://platform.openai.com/docs/api-reference",
        url: "https://api.openai.com/v1",
        key: "",
        models: { method: "GET", url: "/models" },
        llmChat: { method: "POST", url: "/responses" },
        balance: { method: "GET", url: "" },
        textToImage: { method: "POST", url: "/images/generations" },
        imageToText: { method: "GET", url: "" },
        textToVideo: { method: "GET", url: "" },
        speechToText: { method: "GET", url: "" },
        textToSpeech: { method: "GET", url: "" },
      },
      selectedTypes: [],
      selectedSubProviders: [],
      activeStatus: ModelActiveStatus.All,
    },
  ]
}
