import { IconifyJSON } from "@iconify/types"
import { getIconHTML } from "@renderer/components/SvgPicker"
import { ModelType, ProviderMeta, ModelActiveStatus } from "@renderer/types"
export const providerDefault = (providerSvgIcon: IconifyJSON): ProviderMeta[] => {
  return [
    {
      name: "deepseek",
      logo: getIconHTML(providerSvgIcon, "deepseek"),
      alias: "深度求索",
      api: {
        doc: "https://api-docs.deepseek.com/zh-cn/",
        url: "https://api.deepseek.com",
        key: "",
        models: { method: "GET", url: "/models" },
        llmChat: { method: "POST", url: "/chat/completions" },
        balance: { method: "GET", url: "/user/balance" },
        textToImage: { method: "GET", url: "" },
        imageToText: { method: "GET", url: "" },
        textToVideo: { method: "GET", url: "" },
        speechToText: { method: "GET", url: "" },
        textToSpeech: { method: "GET", url: "" },
      },
      selectedTypes: [ModelType.Chat, ModelType.ChatReasoner],
      selectedSubProviders: ["deepseek"],
      activeStatus: ModelActiveStatus.All,
    },
    {
      name: "siliconflow",
      alias: "硅基流动",
      logo: getIconHTML(providerSvgIcon, "siliconflow"),
      api: {
        doc: "https://docs.siliconflow.cn/cn/api-reference",
        url: "https://api.siliconflow.cn/v1",
        key: "",
        models: { method: "GET", url: "/models" },
        llmChat: { method: "POST", url: "/chat/completions" },
        balance: { method: "GET", url: "/user/info" },
        textToImage: { method: "POST", url: "/images/generations" },
        imageToText: { method: "GET", url: "" },
        textToVideo: { method: "GET", url: "" },
        speechToText: { method: "GET", url: "" },
        textToSpeech: { method: "GET", url: "" },
      },
      selectedTypes: [ModelType.Chat, ModelType.ChatReasoner],
      selectedSubProviders: [],
      activeStatus: ModelActiveStatus.All,
    },
    {
      name: "volcengine",
      alias: "火山引擎",
      logo: getIconHTML(providerSvgIcon, "volcengine"),
      api: {
        doc: "https://www.volcengine.com/docs/82379/1263272",
        url: "https://ark.cn-beijing.volces.com/api/v3",
        key: "",
        models: { method: "GET", url: "" },
        llmChat: { method: "POST", url: "/chat/completions" },
        balance: { method: "GET", url: "" },
        textToImage: { method: "GET", url: "" },
        imageToText: { method: "GET", url: "" },
        textToVideo: { method: "GET", url: "" },
        speechToText: { method: "GET", url: "" },
        textToSpeech: { method: "GET", url: "" },
      },
      selectedTypes: [ModelType.Chat, ModelType.ChatReasoner],
      selectedSubProviders: [],
      activeStatus: ModelActiveStatus.All,
    },
    {
      name: "openai",
      alias: "OpenAI",
      logo: getIconHTML(providerSvgIcon, "openai"),
      api: {
        doc: "https://platform.openai.com/docs/api-reference",
        url: "https://api.openai.com",
        key: "",
        models: { method: "GET", url: "/models" },
        llmChat: { method: "POST", url: "/chat/completions" },
        balance: { method: "GET", url: "" },
        textToImage: { method: "POST", url: "/images/generations" },
        imageToText: { method: "GET", url: "" },
        textToVideo: { method: "GET", url: "" },
        speechToText: { method: "GET", url: "" },
        textToSpeech: { method: "GET", url: "" },
      },
      selectedTypes: [],
      selectedSubProviders: [],
      activeStatus: ModelActiveStatus.All,
    },
  ]
}
