import { CombineTableProps } from "./types"
import { merge } from "@toolmain/shared"

export const defaultTableProps = (preset?: CombineTableProps): CombineTableProps => {
  return merge(
    {},
    {
      // data: [],
      // height: null,
      // maxHeight: null,
      stripe: false,
      border: false,
      // size: null,
      fit: true,
      showHeader: true,
      highlightCurrentRow: false,
      // currentRowKey: null,
      // rowClassName: null,
      // rowStyle: null,
      // cellClassName: null,
      // cellStyle: null,
      // headerRowClassName: null,
      // headerRowStyle: null,
      // headerCellClassName: null,
      // headerCellStyle: null,
      // rowKey: null,
      emptyText: "No Data",
      defaultExpandAll: false,
      // expandRowKeys: null,
      // defaultSort: null,
      tooltipEffect: "dark",
      tooltipOptions: {},
      // appendFilterPanelTo: null,
      showSummary: false,
      sumText: "Sum",
      // summaryMethod: null,
      // spanMethod: null,
      selectOnIndeterminate: true,
      indent: 16,
      lazy: false,
      // load: null,
      treeProps: {},
      tableLayout: "fixed",
      scrollbarAlwaysOn: false,
      // showOverflowTooltip: null,
      flexible: false,
      // scrollbarTabindex: null,
      allowDragLastColumn: true,
      // tooltipFormatter: null,
      preserveExpandedContent: false,
      nativeScrollbar: false,
    },
    preset
  )
}
