import { HttpStatusCode, Method } from "@toolmain/shared"
export type RAGEmbeddingConfig = {
  /**
   * unique id
   */
  id: string
  /**
   * custom config name
   */
  name: string
  /**
   * provider embedding api info
   */
  embedding: {
    providerName: string
    model: string
    api: string
    apiKey?: string
    /**
     * @default post
     */
    method?: Method
  }
  /**
   * provider rerank api info
   */
  rerank?: {
    providerName: string
    model: string
    api: string
    apiKey?: string
    /**
     * @default post
     */
    method?: Method
  }
  /**
   * dimensions of the embedding vector
   */
  dimensions: number
  /**
   * max tokens of each chunk
   * @default 512
   */
  maxTokens?: number
  /**
   * max inputs array length when using embedding api
   * @default 20
   */
  maxInputs?: number
  /**
   * split text into chunks, the chunks of text must less than `maxFileChunks`
   *
   * @default 512
   */
  maxFileChunks?: number
}

/**
 * data storage in vector database
 */
export type RAGFile = {
  /**
   * unique record id
   */
  id: string
  /**
   * current vector of the file's current chunk
   */
  vector: number[]
  /**
   * file id
   */
  fileId: string
  /**
   * embedding config id, indicates this record was generated by which embedding config
   */
  configId: string
  /**
   * specify the scope of current file
   */
  topicId: string
  content: string
  fileName: string
  fileSize: number
  chunkIndex: number
  filePath: string
  mimeType?: string
  /**
   * tokens was calcalated for this string content
   */
  tokens?: number
  /**
   * distance between query vector and this record's vector, returned by vector store
   */
  _distance?: number
}

export type RAGSearchParam = {
  content: string
  /**
   * specify the scope of current search, generally, it's the knowledge base id
   */
  topicId: string
  /**
   * `sessionId` marks current searching, genereally, it's the chat-message id.
   * it is used to stop/identify the searching, user must specify a `sessionId` when searching.
   * this `sessionId` will be used to stop the searching
   */
  sessionId: string
}

export type RAGSearchResult = {
  id: string
  score: number
  content: string
  fileId: string
  filename: string
  mimeType: string
}
export enum RagSearchStatus {
  Pending = "pending",
  Success = "success",
  Failed = "failed",
  Aborted = "aborted",
}
export type RAGSearchTask = RAGSearchParam & {
  status: RagSearchStatus
  msg?: string
  code?: HttpStatusCode
  controler?: AbortController
  result?: RAGFile[]
}
export enum RAGFileStatus {
  Processing = "Processing",
  Success = "Success",
  Failed = "Failed",
}

/**
 * TODO: more file type support: url, text, ect.
 */
export interface RAGLocalFileMeta {
  /**
   * file's unique id
   */
  id: string
  /**
   * file's local absolute path
   */
  path: string
  /**
   * specify the scope of current file, generally, it's the knowledge base id
   */
  topicId: string
}

export interface RAGLocalFileInfo extends RAGLocalFileMeta {
  fileName: string
  fileSize: number
  mimeType?: string
  extension?: string
  status?: RAGFileStatus
  code?: HttpStatusCode
  msg?: string
}
