import { Method } from "@toolmain/shared"
export type RAGEmbeddingConfig = {
  /**
   * unique id
   */
  id: string
  /**
   * custom config name
   */
  name: string
  /**
   * provider embedding api info
   */
  embedding: {
    providerName: string
    model: string
    api: string
    apiKey?: string
    /**
     * @default post
     */
    method?: Method
  }
  /**
   * provider rerank api info
   */
  rerank?: {
    providerName: string
    model: string
    api: string
    apiKey?: string
    /**
     * @default post
     */
    method?: Method
  }
  /**
   * dimensions of the embedding vector
   *
   */
  dimensions: number
  /**
   * max tokens of each chunk
   *
   * @default 512
   */
  maxTokens?: number
  /**
   * max inputs array length when using embedding api
   * @default 20
   */
  maxInputs?: number
  /**
   * split text into chunks, the chunks of text must less than `maxFileChunks`
   *
   * @default 512
   */
  maxFileChunks?: number
}

/**
 * data storage in vector database
 */
export type RAGFile = {
  /**
   * unique record id
   */
  id: string
  /**
   * current vector of the file's current chunk
   */
  vector: number[]
  /**
   * file id
   */
  fileId: string
  /**
   * embedding config id, indicates this record was generated by which embedding config
   */
  configId: string
  topicId: string
  content: string
  fileName: string
  fileSize: number
  chunkIndex: number
  mimeType?: string
  /**
   * tokens was calcalated for this string content
   */
  tokens?: number
}

export type RAGSearchParam = {
  content: string
  topicId: string
}

export type RAGSearchResult = {
  id: string
  score: number
  content: string
  fileId: string
  filename: string
  mimeType: string
}

export enum RAGFileStatus {
  Processing = "Processing",
  Success = "Success",
  Failed = "Failed",
  /**
   * indicate the whole tasks are finished
   */
  Finish = "Finish",
}

export interface RAGLocalFileMeta {
  /**
   * file's unique id
   */
  id: string
  /**
   * file's local absolute path
   */
  path: string
  /**
   * specify the scope of current file, if not set,the file will be used for all topics
   */
  topicId: string
}

export interface RAGLocalFileInfo extends RAGLocalFileMeta {
  fileName: string
  fileSize: number
  mimeType?: string
}
